### PR TITLE
Update additional dictionary file.

### PR DESCRIPTION
**Pull request by zivy**
Added GDCMSeriesIDs to the dictionary.

### CODE REVIEW

**Comment by zivy** [comment]
Should the additional_dictionary.txt file be moved to the repository which uses the spell checking? 

That way each repository has its own small "additional dictionary" vs. one mega dictionary. Not sure about this as I think the SimpleITK main repo is the only one using this code, but maybe not.

**Review by blowekamp — APPROVED** [review]

**Comment by blowekamp** [comment]
@zivy I think that is a good idea. At some point I worked on making a pyproject.toml file for this project to be installable, but ran into a problem with including data, i.e. the additional dictionary.

**Comment by blowekamp** [comment]
@zivy It looks like it can already be done with the `-dict` flag: https://github.com/SimpleITK/SimpleITKSpellChecking/blob/main/codespell.py#L161-L163

**Comment by zivy** [comment]
@blowekamp Where should the additional dictionary go in the main SimpleITK repo? Looking at the directory structure possibly add it under Utilities?

**Comment by blowekamp** [comment]
Or in .github/workflows?

**Comment by zivy** [comment]
Much better (why didn't I think of that 😃).

**Pull request merged**
