### PR TITLE
Sitk example words

### PR DESCRIPTION
**Pull request by dave3d**
Added words to the dictionary taken from the SimpleITK examples.  Also addresses the following issue:
https://github.com/SimpleITK/SimpleITKSpellChecking/issues/13

### CODE REVIEW

**Review by zivy — CHANGES_REQUESTED** [review]
Is this the right place for the update? The additional dictionary is per repository, so should be updated in the SimpleITK repo. The spellchecker repo additional dictionary file doesn't need to be updated, unless this is relevant for the testing.

**Comment by dave3d** [comment]
> Is this the right place for the update? The additional dictionary is per repository, so should be updated in the SimpleITK repo. The spellchecker repo additional dictionary file doesn't need to be updated, unless this is relevant for the testing.

Yeah, I dunno.  I was going to update the dictionary in the SimpleITK repo too.

**Comment by zivy** [comment]
There's no need to update the additional_dictionary.txt file here. This repository's additional_dictionary.txt should be minimal used as part of the spell checker testing. Each external repository is responsible for maintaining its own additional_dictionary.txt. I think you can delete this PR, no need for it unless the additional words are used in the testing.

**Comment by dave3d** [comment]
But then should I just remove the dictionary all together from this repo?

**Comment by zivy** [comment]
I don't think so, it should be used in the testing so that it is clear that using the additional dict works (so that we know those other repositories can use an additional dictionary).

**Pull request closed without merging**
